# frozen_string_literal: true

require "spec_helper"
require "pathname"
require "tmpdir"

describe GithubFlowReadiness::Checks do
  let(:playground) { Pathname.new(Dir.mktmpdir("cpflow-github-flow-readiness-checks")) }
  let(:service) { instance_double(GithubFlowReadinessService, root_path: playground) }

  after do
    FileUtils.remove_entry(playground.to_s) if playground.exist?
  end

  def write_file(relative_path)
    path = playground.join(relative_path)
    FileUtils.mkdir_p(path.dirname)
    File.write(path, "# generated by spec\n")
  end

  describe GithubFlowReadiness::Checks::RailsApp do
    it "passes when the Rails scaffold files exist" do
      %w[Gemfile bin/rails config/application.rb config.ru].each { |path| write_file(path) }

      result = described_class.new(service).call

      expect(result.status).to eq(:pass)
      expect(result.message).to include("Rails app scaffold found")
    end

    it "fails listing only the missing scaffold files" do
      %w[Gemfile config.ru].each { |path| write_file(path) }

      result = described_class.new(service).call

      expect(result.status).to eq(:fail)
      expect(result.message).to eq("Missing Rails runtime scaffold: `bin/rails`, `config/application.rb`.")
    end
  end

  describe GithubFlowReadiness::Checks::RubyVersion do
    def result_for(version)
      allow(service).to receive(:inferred_ruby_version)
        .and_return(version && Gem::Version.new(version))
      described_class.new(service).call
    end

    it "warns when the Ruby version cannot be determined" do
      result = result_for(nil)

      expect(result.status).to eq(:warn)
      expect(result.message).to eq("Could not determine the app Ruby version.")
    end

    it "passes for a supported Ruby version" do
      result = result_for("3.3.7")

      expect(result.status).to eq(:pass)
      expect(result.message).to eq("Ruby 3.3.7 is modern enough for rollout.")
    end

    it "fails for a legacy Ruby version" do
      result = result_for("3.2.9")

      expect(result.status).to eq(:fail)
      expect(result.message).to include("Ruby 3.2.9 is legacy.")
    end
  end

  describe GithubFlowReadiness::Checks::BundlerVersion do
    def result_for(version)
      allow(service).to receive(:lockfile_bundler_version)
        .and_return(version && Gem::Version.new(version))
      described_class.new(service).call
    end

    it "warns when the Bundler version cannot be determined" do
      result = result_for(nil)

      expect(result.status).to eq(:warn)
      expect(result.message).to eq("Could not determine the Bundler version from `Gemfile.lock`.")
    end

    it "passes for a supported Bundler version" do
      result = result_for("2.5.22")

      expect(result.status).to eq(:pass)
      expect(result.message).to eq("Bundler 2.5.22 is modern enough for rollout.")
    end

    it "fails for a legacy Bundler version" do
      result = result_for("1.17.3")

      expect(result.status).to eq(:fail)
      expect(result.message).to include("Bundler 1.17.3 is legacy.")
    end
  end

  describe GithubFlowReadiness::Checks::Dockerfile do
    it "passes when a root Dockerfile exists" do
      write_file("Dockerfile")

      result = described_class.new(service).call

      expect(result.status).to eq(:pass)
      expect(result.message).to eq("Found production Dockerfile at `Dockerfile`.")
    end

    it "passes when only the .controlplane Dockerfile exists" do
      write_file(".controlplane/Dockerfile")

      result = described_class.new(service).call

      expect(result.status).to eq(:pass)
      expect(result.message).to eq("Found production Dockerfile at `.controlplane/Dockerfile`.")
    end

    it "fails when no Dockerfile exists" do
      result = described_class.new(service).call

      expect(result.status).to eq(:fail)
      expect(result.message).to include("No production Dockerfile found")
    end
  end

  describe GithubFlowReadiness::Checks::SqliteProduction do
    it "returns nothing when production does not use SQLite" do
      allow(service).to receive(:sqlite_database_in_production?).and_return(false)

      expect(described_class.new(service).call).to be_nil
    end

    it "returns an info result when production uses SQLite" do
      allow(service).to receive(:sqlite_database_in_production?).and_return(true)

      result = described_class.new(service).call

      expect(result.status).to eq(:info)
      expect(result.message).to include("Production database config uses SQLite.")
    end
  end

  describe GithubFlowReadiness::Checks::GemSources do
    it "passes when all direct gems come from public RubyGems" do
      dependencies = [{ name: "rails" }, { name: "puma" }]
      allow(service).to receive_messages(gem_dependencies: dependencies)
      allow(service).to receive(:public_rubygems_dependency?).and_return(true)

      result = described_class.new(service).call

      expect(result.status).to eq(:pass)
      expect(result.message).to eq("All direct Ruby gems resolve from public RubyGems sources.")
    end

    it "warns listing non-public gems sorted by name" do
      dependencies = [{ name: "rails" }, { name: "zeta_gem" }, { name: "alpha_gem" }]
      allow(service).to receive_messages(gem_dependencies: dependencies)
      allow(service).to receive(:public_rubygems_dependency?) { |dependency| dependency[:name] == "rails" }

      result = described_class.new(service).call

      expect(result.status).to eq(:warn)
      expect(result.message).to include("`alpha_gem`, `zeta_gem`")
    end
  end

  describe GithubFlowReadiness::Checks::GemExactPins do
    it "delegates to the service registry check" do
      registry_check = instance_double(GithubFlowReadinessService::RegistryCheck)
      registry_result = GithubFlowReadiness::Result.new(status: :pass, message: "all pinned gems available")
      allow(service).to receive_messages(rubygems_registry_check: registry_check)
      allow(service).to receive(:exact_pin_registry_result).with(registry_check).and_return(registry_result)

      expect(described_class.new(service).call).to be(registry_result)
    end
  end

  describe GithubFlowReadiness::Checks::NpmExactPins do
    it "returns the parse error result when package.json cannot be parsed" do
      parse_error_result = GithubFlowReadiness::Result.new(status: :warn, message: "could not parse")
      allow(service).to receive_messages(
        package_json_parse_error: true,
        package_json_parse_error_result: parse_error_result
      )

      expect(described_class.new(service).call).to be(parse_error_result)
    end

    it "delegates to the service registry check when package.json parses" do
      registry_check = instance_double(GithubFlowReadinessService::RegistryCheck)
      registry_result = GithubFlowReadiness::Result.new(status: :pass, message: "all pinned packages available")
      allow(service).to receive_messages(
        package_json_parse_error: false,
        npm_registry_check: registry_check
      )
      allow(service).to receive(:exact_pin_registry_result).with(registry_check).and_return(registry_result)

      expect(described_class.new(service).call).to be(registry_result)
    end
  end
end
