kind: gvc
name: {{APP_NAME}}
spec:
  env:
    - name: DATABASE_URL
      value: postgres://postgres:password@postgres.{{APP_NAME}}.cpln.local:5432/{{APP_NAME}}
    - name: SECRET_KEY_BASE
      value: "123"
  staticPlacement:
    locationLinks:
      - {{APP_LOCATION_LINK}}
---
kind: identity
name: {{APP_IDENTITY}}
