PreCommit:
  RubyAutoFix:
    enabled: true
    parallelize: false
    required_executable: "./script/precommit/ruby_autofix"
    command: ["./script/precommit/ruby_autofix", "staged"]
    requires_files: true
    include:
      - "**/*.rb"
      - "**/*.rake"
      - "**/*.ru"

  TrailingNewlines:
    enabled: true
    parallelize: false
    required_executable: "./script/precommit/check_trailing_newlines"
    command: ["./script/precommit/check_trailing_newlines", "staged"]
    requires_files: true
    include:
      - "**/*"

  ValidateLinks:
    enabled: true
    required_executable: "./script/precommit/check_cpln_links"
    command: ["./script/precommit/check_cpln_links", "staged"]
    requires_files: true
    include:
      - "**/*.md"

  CommandDocs:
    enabled: true
    required_executable: "./script/precommit/check_command_docs"
    command: ["./script/precommit/check_command_docs", "staged"]
    requires_files: true
    include:
      - "lib/command/**/*.rb"
      - "docs/commands.md"
      - "script/update_command_docs"
      - "script/check_command_docs"
      - "Rakefile"

  RuboCop:
    enabled: true
    on_warn: fail
    required_executable: "./script/precommit/ruby_lint"
    command: ["./script/precommit/ruby_lint", "staged"]
    requires_files: true
    include:
      - "**/*.rb"
      - "**/*.rake"
      - "**/*.ru"

# PrePush:
#   RSpec:
#     enabled: true
#     command: ["bundle", "exec", "rspec"]
