PreCommit:
  ValidateLinks:
    enabled: true
    command: ["bash", "./script/check_cpln_links"]
  CommandDocs:
    enabled: true
    command: ["bundle", "exec", "rake", "check_command_docs"]
  RuboCop:
    enabled: true
    on_warn: fail
    command: ["bundle", "exec", "rubocop"]

# PrePush:
#   RSpec:
#     enabled: true
#     command: ["bundle", "exec", "rspec"]
