PreCommit:
  CommandDocs:
    enabled: true
    command: ["bundle", "exec", "rake", "check_command_docs"]
  RuboCop:
    enabled: true
    on_warn: fail
    command: ["bundle", "exec", "rubocop"]

PrePush:
  RSpec:
    enabled: true
    command: ["bundle", "exec", "rspec"]
