#!/bin/sh

SCRIPT_DIR=$(dirname $(realpath $0))

# exports .env to vars
#
# Example .env:
# CPLN_TOKEN=xxx
#
if [ -f "$SCRIPT_DIR/.env" ]; then
  export $(grep -v '^#' $SCRIPT_DIR/.env | xargs -0)
fi

# exec $SCRIPT_DIR/old_commands/main.sh "$@"
exec ruby $SCRIPT_DIR/lib/main.rb "$@"
