default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
  port: <%= ENV["DB_PORT"] || "5432" %>
  username: <%= ENV["DB_USER"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: dummy_development

test:
  <<: *default
  database: dummy_test

production:
  <<: *default
  database: dummy_production
