# frozen_string_literal: true

ENV["RAILS_ENV"] ||= "test"
ENV["HIDE_COMMAND_OUTPUT"] = "true"
ENV["DISABLE_INTERRUPT_TRAP"] = "true"
ENV["DISABLE_VALIDATIONS"] = "true"
ENV["DISABLE_APPLY_READY"] = "true"

require "rspec/retry"
require "simplecov"
require "timecop"

SimpleCov.start do
  enable_coverage :branch

  # The 2026-07-10 green CI fast-suite baseline is 85.32% line coverage.
  # Gate only the full CI fast command so local, slow, and specific-path runs can report partial coverage.
  # Re-baseline from a green CI fast-suite artifact before changing this value.
  # Inspect only the standard RSpec flags used by the fast CI command. Unknown options fail the
  # matching CI invocation, avoiding a second RSpec argument parse and silent coverage-gate drift.
  ci_arguments = ARGV.dup
  excludes_slow_specs = false
  explicit_spec_paths = false
  unrecognized_ci_option = false

  while (argument = ci_arguments.shift)
    case argument
    when "--tag", "-t"
      excludes_slow_specs ||= ci_arguments.shift == "~slow"
    when /\A(?:--tag=|-t)(.+)\z/
      excludes_slow_specs ||= Regexp.last_match(1) == "~slow"
    when "--format", "-f", "--out", "-o", "--order", "--seed", "--require", "-r", "--load-path", "-I"
      ci_arguments.shift
    when /\A(?:--format|--out|--order|--seed|--require|--load-path)=/, /\A-(?:f|o|r|I).+/
      # This option carries its value inline.
    else
      if argument.start_with?("-")
        unrecognized_ci_option = true
      else
        explicit_spec_paths = true
      end
    end
  end

  if ENV["CI"] == "true" && excludes_slow_specs && unrecognized_ci_option
    raise "Unrecognized RSpec option in the fast CI coverage invocation; update coverage-floor detection."
  end

  full_fast_ci = ENV["CI"] == "true" && excludes_slow_specs && !explicit_spec_paths
  minimum_coverage line: 84 if full_fast_ci

  enable_for_subprocesses true
  at_fork do |pid|
    # This needs a unique name so it won't be overwritten
    command_name "#{SimpleCov.command_name} (subprocess: #{pid})"

    print_error_status false
    formatter SimpleCov::Formatter::SimpleFormatter
    minimum_coverage 0

    start do
      enable_coverage :branch
    end
  end
end

require_relative "../lib/cpflow"

# Cross-file dependencies must be declared with require_relative, not assumed from load order.
Dir["#{__dir__}/support/**/*.rb"].each { |f| require f }

# ControlplaneApiDirect#call raises a bare RuntimeError for unexpected HTTP
# responses, with a message like "#<Net::HTTPInternalServerError:0x...> body".
# Match only the transient subset (5xx server errors and 429 rate limiting) so
# rspec-retry can retry those alongside the socket-level failures below.
module TransientServerHTTPError
  RESPONSE_CLASSES = %w[
    InternalServerError NotImplemented BadGateway ServiceUnavailable
    GatewayTimeout VersionNotSupported VariantAlsoNegotiates
    InsufficientStorage LoopDetected NotExtended
    NetworkAuthenticationRequired ServerError TooManyRequests
  ].freeze
  MESSAGE_PATTERN = /\A#<Net::HTTP(?:#{RESPONSE_CLASSES.join('|')})\b/

  def self.===(exception)
    exception.is_a?(RuntimeError) && exception.message.match?(MESSAGE_PATTERN)
  end
end

# Transient failure matchers for rspec-retry's `exceptions_to_retry`. Only
# failures matching these are ever retried; assertion failures and other
# deterministic errors always fail on the first attempt. `Timeout::Error`
# covers `Net::OpenTimeout`/`Net::ReadTimeout` raised inside example code.
# Example-level hangs interrupted by the tiered `Timeout.timeout` hook below
# are NOT retried: the timeout gem (>= 0.2) interrupts the example thread
# with `Timeout::ExitException` (an `Exception`, not a `Timeout::Error`),
# which rspec-core records as the example's exception before the timeout
# block can convert it. A hung example therefore intentionally fails fast on
# the first attempt instead of tripling the stall through retries.
TRANSIENT_FAILURE_MATCHERS = [
  Errno::ECONNREFUSED,
  Errno::ECONNRESET,
  Errno::EHOSTUNREACH,
  Errno::ENETUNREACH,
  Errno::EPIPE,
  Errno::ETIMEDOUT,
  EOFError,
  OpenSSL::SSL::SSLError,
  SocketError,
  Timeout::Error,
  TransientServerHTTPError
].freeze

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # The settings below are suggested to provide a good initial experience
  # with RSpec, but feel free to customize to your heart's content.
  #   # This allows you to limit a spec run to individual examples or groups
  #   # you care about by tagging them with `:focus` metadata. When nothing
  #   # is tagged with `:focus`, all examples get run. RSpec also provides
  #   # aliases for `it`, `describe`, and `context` that include `:focus`
  #   # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  #   config.filter_run_when_matching :focus
  #
  #   # Allows RSpec to persist some state between runs in order to support
  #   # the `--only-failures` and `--next-failure` CLI options. We recommend
  #   # you configure your source control system to ignore this file.
  #   config.example_status_persistence_file_path = "spec/examples.txt"
  #
  #   # Limits the available syntax to the non-monkey patched syntax that is
  #   # recommended. For more details, see:
  #   # https://relishapp.com/rspec/rspec-core/docs/configuration/zero-monkey-patching-mode
  #   config.disable_monkey_patching!
  #
  #   # This setting enables warnings. It's recommended, but in some cases may
  #   # be too noisy due to issues in dependencies.
  #   config.warnings = true
  #
  #   # Many RSpec users commonly either run the entire suite or an individual
  #   # file, and it's useful to allow more verbose output when running an
  #   # individual spec file.
  #   if config.files_to_run.one?
  #     # Use the documentation formatter for detailed output,
  #     # unless a formatter has already been configured
  #     # (e.g. via a command-line flag).
  #     config.default_formatter = "doc"
  #   end
  #
  #   # Print the 10 slowest examples and example groups at the
  #   # end of the spec run, to help surface which specs are running
  #   # particularly slow.
  #   config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed

  config.include CommandHelpers
  config.include DateTimeHelpers
  config.include DirectoryHelpers
  config.include StubENV
  config.include VerifiedDouble

  config.verbose_retry = true
  config.display_try_failure_messages = true

  # `Integer(...)` (not `||`) normalizes RSPEC_RETRY_COUNT to a number.
  # rspec-retry itself calls `.to_i` and clamps to a minimum of one attempt,
  # so both 0 and 1 mean "single attempt, no retries". The normalization makes
  # empty or garbage values raise ArgumentError at load time instead of
  # silently degrading to a single attempt via `"".to_i`.
  config.default_retry_count = Integer(ENV.fetch("RSPEC_RETRY_COUNT", "3"))

  # Retry only transient live-API failures (network, timeout, 5xx/429).
  # Deterministic failures (assertion errors, argument errors, etc.) fail on
  # the first attempt everywhere, including live runs.
  config.exceptions_to_retry = TRANSIENT_FAILURE_MATCHERS

  config.before(:suite) do
    if CommandHelpers.cpln_org_configured?
      DummyAppSetup.setup
    else
      CommandHelpers.configure_config_file
    end
  end

  config.after(:suite) do
    if CommandHelpers.cpln_org_configured?
      DummyAppSetup.cleanup unless ENV.fetch("SKIP_CLEANUP", nil) == "true"
    else
      CommandHelpers.delete_config_file
    end
  end

  config.before do
    allow(Cpflow::Cli).to receive(:check_cpln_version)
    allow(Cpflow::Cli).to receive(:check_cpflow_version)
  end

  # Per-example timeout, tiered by suite type:
  # - Live runs (CPLN_ORG configured) keep the original 10-minute budget, since
  #   untagged live specs (image builds, deploys) can legitimately take minutes.
  # - Offline/unit runs (no org configured) get 60 seconds, so a hung example
  #   fails fast instead of stalling the run.
  # - :slow examples get the 10-minute budget in all runs.
  config.around do |example|
    timeout = if CommandHelpers.cpln_org_configured? || example.metadata[:slow]
                600
              else
                60
              end
    Timeout.timeout(timeout) { example.run }
  end

  config.around(:example, :without_config_file) do |example|
    CommandHelpers.delete_config_file
    example.run
    CommandHelpers.configure_config_file
  end

  config.around(:example, :enable_validations) do |example|
    ENV["DISABLE_VALIDATIONS"] = "false"
    example.run
    ENV["DISABLE_VALIDATIONS"] = "true"
  end
end
