name: Check Links

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check_cpln_links:
    runs-on: ubuntu-latest
    name: Check Links
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Validate outgoing links to Control Plane
        run: |
          TERM=xterm-color ./script/check_cpln_links
        shell: bash
