name: Check Links

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_cpln_links:
    runs-on: ubuntu-latest
    name: Check Links
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate outgoing links to Control Plane
        run: |
          TERM=xterm-color ./script/check_cpln_links
        shell: bash
