name: Command Docs

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: Command Docs
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@bec3f19a76460dbe12f60def7d1a77585f07516c # v1.322.0
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Check if command docs are up to date
        run: bundle exec rake check_command_docs
