name: Command Docs

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: Command Docs
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Check if command docs are up to date
        run: bundle exec rake check_command_docs
