name: RSpec

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rspec:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ruby:
          - "2.7"
          - "3.0"
    runs-on: ${{ matrix.os }}
    name: RSpec
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.ruby }}
          path: coverage
