name: RSpec Specific

on:
  workflow_dispatch:
    inputs:
      spec_paths:
        description: "Test files or directories that should be run"
        required: true

jobs:
  rspec-specific:
    name: RSpec (Specific)
    uses: ./.github/workflows/rspec-shared.yml
    with:
      os_version: ubuntu-latest
      ruby_version: "3.2"
      spec_paths: ${{ inputs.spec_paths }}
    secrets: inherit
