name: RSpec

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  rspec-fast:
    name: RSpec (Fast)
    uses: ./.github/workflows/rspec-shared.yml
    with:
      os_version: ubuntu-latest
      ruby_version: "3.2"
      test_tag: ~slow
    secrets: inherit

  rspec-slow:
    name: RSpec (Slow)
    uses: ./.github/workflows/rspec-shared.yml
    if: github.event_name == 'workflow_dispatch'
    with:
      os_version: ubuntu-latest
      ruby_version: "3.2"
      test_tag: slow
    secrets: inherit
